
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Mar 02 13:58:24 EST 2014
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DISP = 16;
  public static final int REGISTER = 2;
  public static final int INT = 20;
  public static final int RPAREN = 19;
  public static final int BEQ = 6;
  public static final int RAND = 10;
  public static final int DISPL = 11;
  public static final int LPAREN = 18;
  public static final int SUB = 14;
  public static final int LB = 9;
  public static final int JUMP = 7;
  public static final int EOF = 0;
  public static final int ADD = 4;
  public static final int error = 1;
  public static final int HALT = 15;
  public static final int IMMEDIATE = 17;
  public static final int XOR = 13;
  public static final int SB = 8;
  public static final int ADDI = 5;
  public static final int LABEL = 3;
  public static final int SLT = 12;
}

