
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Oct 13 12:34:26 EDT 2012
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int REGISTER = 2;
  public static final int RPAREN = 8;
  public static final int INT = 11;
  public static final int DATA = 10;
  public static final int I_OPT = 6;
  public static final int LPAREN = 7;
  public static final int COLON = 14;
  public static final int EOL = 13;
  public static final int STRING = 16;
  public static final int EOF = 0;
  public static final int NEWLINE = 12;
  public static final int error = 1;
  public static final int ASCIIZ = 17;
  public static final int IMMEDIATE = 15;
  public static final int TEXT = 9;
  public static final int R_OPT = 5;
  public static final int LABEL = 3;
  public static final int J_OPT = 4;
}

