
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Oct 28 18:00:46 EDT 2012
//----------------------------------------------------

package tools;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int PERIOD = 33;
  public static final int LPAREN = 27;
  public static final int INT = 3;
  public static final int PRINTLN = 18;
  public static final int OUT = 17;
  public static final int STATIC = 10;
  public static final int RPAREN = 30;
  public static final int SEMICOLON = 31;
  public static final int COMMA = 32;
  public static final int OP = 35;
  public static final int CLASS = 19;
  public static final int MAIN = 12;
  public static final int IF = 14;
  public static final int THIS = 24;
  public static final int EOF = 0;
  public static final int BOOLEAN = 5;
  public static final int SYSTEM = 16;
  public static final int RETURN = 20;
  public static final int EQUAL = 34;
  public static final int TRUE = 7;
  public static final int NEW = 21;
  public static final int error = 1;
  public static final int LSQBRACKET = 26;
  public static final int IDENT = 2;
  public static final int VOID = 11;
  public static final int LBRACE = 25;
  public static final int ELSE = 22;
  public static final int WHILE = 15;
  public static final int PUBLIC = 9;
  public static final int RBRACE = 28;
  public static final int EXTENDS = 13;
  public static final int RSQBRACKET = 29;
  public static final int STRING = 6;
  public static final int FALSE = 8;
  public static final int INT_LIT = 4;
  public static final int LENGTH = 23;
}

