
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Oct 29 12:40:19 EDT 2012
//----------------------------------------------------

package tools;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int PERIOD = 34;
  public static final int LPAREN = 28;
  public static final int INT = 4;
  public static final int PRINTLN = 19;
  public static final int OUT = 18;
  public static final int STATIC = 11;
  public static final int RPAREN = 31;
  public static final int SEMICOLON = 32;
  public static final int COMMA = 33;
  public static final int OP = 3;
  public static final int CLASS = 20;
  public static final int MAIN = 13;
  public static final int IF = 15;
  public static final int THIS = 25;
  public static final int EOF = 0;
  public static final int BOOLEAN = 5;
  public static final int SYSTEM = 17;
  public static final int RETURN = 21;
  public static final int EQUAL = 35;
  public static final int TRUE = 7;
  public static final int NEW = 22;
  public static final int error = 1;
  public static final int LSQBRACKET = 27;
  public static final int IDENT = 2;
  public static final int VOID = 12;
  public static final int LBRACE = 26;
  public static final int ELSE = 23;
  public static final int WHILE = 16;
  public static final int PUBLIC = 10;
  public static final int RBRACE = 29;
  public static final int EXTENDS = 14;
  public static final int RSQBRACKET = 30;
  public static final int STRING = 6;
  public static final int FALSE = 8;
  public static final int INT_LIT = 9;
  public static final int LENGTH = 24;
}

